const Parser = require("binary-parser").Parser;

const loopPacket = new Parser()
  .string("LOO", { length: 3 })
  .uint8("barTrend")
  .uint8("packetType")
  .uint16le("nextRecord")
  .uint16le("pressure")
  .uint16le("indoorTemperature")
  .uint8("indoorHumidity")
  .uint16le("outdoorTemperature")
  .uint8("windSpeed")
  .uint8("windSpeed10Min")
  .uint16le("windDirection")
  .uint8("extraTemps0")
  .uint8("extraTemps1")
  .uint8("extraTemps2")
  .uint8("extraTemps3")
  .uint8("extraTemps4")
  .uint8("extraTemps5")
  .uint8("extraTemps6")
  .uint8("soilTemps0")
  .uint8("soilTemps1")
  .uint8("soilTemps2")
  .uint8("soilTemps3")
  .uint8("leafTemps0")
  .uint8("leafTemps1")
  .uint8("leafTemps2")
  .uint8("leafTemps3")
  .uint8("outdoorHumidity")
  .uint8("extraHumidity0")
  .uint8("extraHumidity1")
  .uint8("extraHumidity2")
  .uint8("extraHumidity3")
  .uint8("extraHumidity4")
  .uint8("extraHumidity5")
  .uint8("extraHumidity6")
  .uint16le("rainRate")
  .uint8("uv")
  .uint16le("solarRadiation")
  .uint16le("stormRain")
  .uint16le("stormStartDate")
  .uint16le("rainDay")
  .uint16le("rainMonth")
  .uint16le("rainYear")
  .uint16le("dayET")
  .uint16le("monthET")
  .uint16le("yearET")
  .uint8("soilMoisture0")
  .uint8("soilMoisture1")
  .uint8("soilMoisture2")
  .uint8("soilMoisture3")
  .uint8("leafWetness0")
  .uint8("leafWetness1")
  .uint8("leafWetness2")
  .uint8("leafWetness3")
  .uint8("insideAlarms")
  .uint8("rainAlarms")
  .string("outsideAlarms", { length: 2 })
  .string("extraTempHumidityAlarms", { length: 8 })
  .string("soilLeafAlarms", { length: 4 })
  .uint8("batteryStatus")
  .uint16le("batteryVolts")
  .uint8("forecastIcon")
  .uint8("forecastRuleNo")
  .uint16le("sunrise")
  .uint16le("sunset")
  .string("eol", { length: 2 })
  .uint16le("crc");

const parseLoopPacket = packet => {
  const parsedPacket = loopPacket.parse(packet);
  return parsedPacket;
};

module.exports = parseLoopPacket;
