const Parser = require("binary-parser").Parser;

const loopPacket = new Parser()
  .string("LOO", { length: 3 })
  .uint8("BarTrend")
  .uint8("PacketType")
  .uint16le("NextRec")
  .uint16le("Pressure")
  .uint16le("TempIn")
  .uint8("HumIn")
  .uint16le("TempOut")
  .uint8("WindSpeed")
  .uint8("WindSpeed10Min")
  .uint16le("WindDir")
  .uint8("ExtraTemps0")
  .uint8("ExtraTemps1")
  .uint8("ExtraTemps2")
  .uint8("ExtraTemps3")
  .uint8("ExtraTemps4")
  .uint8("ExtraTemps5")
  .uint8("ExtraTemps6")
  .uint8("SoilTemps0")
  .uint8("SoilTemps1")
  .uint8("SoilTemps2")
  .uint8("SoilTemps3")
  .uint8("LeafTemps0")
  .uint8("LeafTemps1")
  .uint8("LeafTemps2")
  .uint8("LeafTemps3")
  .uint8("HumOut")
  .uint8("HumExtra0")
  .uint8("HumExtra1")
  .uint8("HumExtra2")
  .uint8("HumExtra3")
  .uint8("HumExtra4")
  .uint8("HumExtra5")
  .uint8("HumExtra6")
  .uint16le("RainRate")
  .uint8("UV")
  .uint16le("SolarRad")
  .uint16le("RainStorm")
  .uint16le("StormStartDate")
  .uint16le("RainDay")
  .uint16le("RainMonth")
  .uint16le("RainYear")
  .uint16le("ETDay")
  .uint16le("ETMonth")
  .uint16le("ETYear")
  .uint8("SoilMoist0")
  .uint8("SoilMoist1")
  .uint8("SoilMoist2")
  .uint8("SoilMoist3")
  .uint8("LeafWetness0")
  .uint8("LeafWetness1")
  .uint8("LeafWetness2")
  .uint8("LeafWetness3")
  .uint8("AlarmIn")
  .uint8("AlarmRain")
  .string("AlarmOut", { length: 2 })
  .string("AlarmExTempHum", { length: 8 })
  .string("AlarmSoilLeaf", { length: 4 })
  .uint8("BatteryStatus")
  .uint16le("BatteryVolts")
  .uint8("ForecastIcon")
  .uint8("ForecastRuleNo")
  .uint16le("SunRise")
  .uint16le("SunSet")
  .string("EOL", { length: 2 })
  .uint16le("CRC");

const parseLoopPacket = packet => {
  const parsedPacket = loopPacket.parse(packet);
  return parsedPacket;
};

module.exports = parseLoopPacket;
